### ISSUE TITLE
Visual overview of connections FNML

### ISSUE THREAD

**Issue by samiscoding** [kg-construct/fnml-spec#13]
I think we need to generalize the _Figure 1 Visual overview of connections FNML_ to also cover the reference to functions as subject and probably predicate, right?

**Comment by samiscoding** [comment]
in fact, I see that the diagram in #8 in generalized so I guess we are just missing in this visualization.

**Comment by dachafra** [comment]
Shall we close this issue then? @samiscoding

**Comment by samiscoding** [comment]
![mermaid-diagram-2023-01-24-165924](https://user-images.githubusercontent.com/12610118/214343691-d4bbb502-556e-4a61-8e86-9f97f15652f0.png)
@bjdmeest what do you think about this modification in the figure?

**Comment by bjdmeest** [comment]
I kept capitalization in line with the (R2)RML specs, but no problem changing it. So maybe you could make or PR, or just add a note to keep them in line with the final spec for now?

**Comment by pmaria** [comment]
@samiscoding I don't get the replacement of `function-valued term map` with `Output Term Map`, and `return ` with `output` . I don't think that's in line with the current draft.

**Comment by bjdmeest** [comment]
> @samiscoding I don't get the replacement of `function-valued term map` with `Output Term Map`, and `return ` with `output` . I don't think that's in line with the current draft.

Ah, good catch, I glossed over that! Yeah that part of the change is not in line with what was last agreed, namely to define it similar to `constant-valued term map`, `template-valued term map`, etc

**Comment by samiscoding** [comment]
my bad! uploaded an old version of the figure. This is what I pushed to the repository
![mermaid-diagram-2023-01-25-155704](https://user-images.githubusercontent.com/12610118/214596985-f0652738-f2f9-4950-a9c9-37087d701f2f.png)

**Comment by bjdmeest** [comment]
Perfect! Closing this as it's added in the spec (and Ana's diagram too :) )
