### ISSUE TITLE
Default term type for function value in object map

### ISSUE THREAD

**Issue by pmaria** [kg-construct/fnml-spec#2]
The spec says that 
> [the default term type depends on whether the term map is an object map or not](https://www.w3.org/TR/r2rml/#termtype).

which points to the R2RML spec which says
>If the term map does not have a `rr:termType` property, then its term type is:
>* rr:Literal, if it is an object map and at least one of the following conditions is true:
>   * It is a column-based term map.
>   * It has a `rr:language` property (and thus a specified language tag).
>   * It has a `rr:datatype` property (and thus a specified datatype).
>* rr:IRI, otherwise.

Reading this I would say an `rr:ObjectMap` that is also a `fnml:FunctionMap` with no `rr:termType`,  ` rr:language` or `rr:datatype` specified should by default return an `rr:IRI`. (Note: this is how it is implemented in CARML currently)

In FnO test case [RMLFNOTC0000-CSV](https://github.com/RMLio/rml-fno-test-cases/tree/master/RMLFNOTC0000-CSV) however, the expected term type in such a case is `rr:Literal`. We need to clarify this.

**Comment by bjdmeest** [comment]
Given the text at https://kg-construct.github.io/fnml-spec/#fnml-outputtermmap, I close this issue with commit  257a79fecf4e185598077cb55315d7ddccd7294a, feel free to reopen
