### ISSUE TITLE
Is the class `fnml:OutputTermMap` necessary?

### ISSUE THREAD

**Issue by pmaria** [kg-construct/fnml-spec#9]
`fnml:OutputTermMap` is now introduced as a type of term map. However, I don't think we should introduce it as such. 
I think we should introduce it as being an aspect of a term map. Just as other expressions can be aspects - `rr:constant` or `rr:template` etc. [In R2RML they talk about](https://www.w3.org/TR/r2rml/#term-map) constant-valued term map, and template-valued term map, etc. So here, we could just talk about function-valued term maps.

Of course we could create specific classes for all possible term map and expression combinations, so you could get a `FunctionValuedGraphMap` for example, but that might not be necessary.

If we do wish to introduce these specific classes I would create class intersections between specific term maps and specific expression maps (expression map is proposed in https://github.com/kg-construct/rml-core/pull/46), but I think we would need to have a good use case for this.

Another reason not to position it as a term map is to be able to use functions in non-term map constructs, e.g. languageMaps or joins as proposed in https://github.com/kg-construct/rml-core/issues/53

**Comment by bjdmeest** [comment]
To answer your question: no, it isn't necessary, fixing to be in line with R2RML now :)
